name: ci-python-ubuntu
on: [
  push,
  pull_request,
]

jobs:
  build:
    name: "python ${{ matrix.python-version }} tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
            # "3.7",
            # "3.8",
            # "3.9",
            # "3.10",
            "3.11",
            "3.12",
        ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip wheel
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Install dependencies
        run: |
          pip install ./python[tests]
      - name: Test
        run: |
          python -m unittest discover --pattern="*test.py" --start-directory python/ee/tests
